name: Deploy website on push
on:
  pull_request:
    types: [closed]
jobs:
  web-deploy:
    name: Deploy website via FTP
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: https://data.forgejo.org/actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5

      - name: Push files via FTP
        uses: https://github.com/SamKirkland/FTP-Deploy-Action@8e83cea8672e3fbcbb9fdafff34debf6ae4c5f65 # v4.3.5
        with:
          server: www250.your-server.de
          server-dir: public_html/
          protocol: ftps
          username: kennyaa
          password: ${{ secrets.ftp_password }}
