name: Deploy website on push
on:
  push:
    branches:
      - main
jobs:
  web-deploy:
    name: Deploy website via FTP
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Push files via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.6
        with:
          server: www250.your-server.de
          server-dir: public_html/
          protocol: ftps
          username: kennyaa
          password: ${{ secrets.ftp_password }}
