on: push
name: ğŸš€ Deploy website on push
jobs:
  web-deploy:
    name: ğŸ‰ Deploy
    runs-on: ubuntu-latest
    steps:
      - name: ğŸšš Get latest code
        uses: https://data.forgejo.org/actions/checkout@v4

      - name: ğŸ” Lint HTML
        run: npx htmlhint "**/*.html"

      - name: ğŸ“‚ Sync files
        uses: https://github.com/SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: www250.your-server.de
          server-dir: public_html/
          protocol: ftps
          username: kennyaa
          password: ${{ secrets.ftp_password }}
